name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: 'Maintenance'
    label: 'chore'
tag-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes


  $CHANGES


